// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaofiqgiukxefcmgxawe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdhb2ZpcWdpdWt4ZWZjbWd4YXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTI2NDQsImV4cCI6MjA3Mzk2ODY0NH0.r53tGdTZ2w1I3H3c3WPn2vlY6pqroH-mXhoswEqIG_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});